# Generated by Django 3.2 on 2021-05-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Adlari_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seher_otel_adi', models.CharField(max_length=20, verbose_name='Otel ADi :')),
                ('seher_otel', models.ImageField(upload_to='', verbose_name='Otel Sekili: ')),
                ('seher_rest_adi', models.CharField(max_length=20, verbose_name='Restoran ADi :')),
                ('seher_rest', models.ImageField(upload_to='', verbose_name='Restoran Sekili: ')),
                ('seher_park_adi', models.CharField(max_length=20, verbose_name='Luna Park ADi :')),
                ('seher_park', models.ImageField(upload_to='', verbose_name='Luna Park Sekili: ')),
                ('seher_cimerlik_adi', models.CharField(max_length=20, verbose_name='Cimerlik ADi :')),
                ('seher_cimerlik', models.ImageField(upload_to='', verbose_name='Cimerlik Sekili: ')),
            ],
        ),
    ]
