# Generated by Django 3.2 on 2021-05-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_service_adlari_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_adlari_2',
            name='seherler',
            field=models.CharField(default=True, max_length=20, verbose_name='Seher Adi: '),
            preserve_default=False,
        ),
    ]
