# Generated by Django 3.2 on 2021-05-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_service_adlari_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_adlari_3',
            name='servis_sekil1',
            field=models.ImageField(default=True, upload_to='', verbose_name='Service Image: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_adlari_3',
            name='servis_sekil2',
            field=models.ImageField(default=True, upload_to='', verbose_name='Service Image: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_adlari_3',
            name='servis_sekil3',
            field=models.ImageField(default=True, upload_to='', verbose_name='Service Image: '),
            preserve_default=False,
        ),
    ]
